### ISSUE TITLE
README command fix

### ISSUE THREAD

**Issue by Navodar22** [samvdb/loxone-weather-proxy#2]
In README command is

```
docker run -p 6066:6066 -e TOMORROW_APIKEY=XXXX samvdb/loxone-weather-proxy
```

I believe it should be

```
docker run -p 6066:6066 -e TOMORROW_APIKEY=XXXX ghcr.io/samvdb/loxone-weather-proxy
```

Otherwise it downloads image from dockerhub and not ghcr. 
In dockerhub image with the latest is even still using DarkSky weather API.

**Comment by samvdb** [comment]
Thank you!
